export const styles = {
  container: {
    maxWidth: '1920px',
    margin: '0 auto',
    padding: '24px',
  },
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '400px',
  },
  pageHeader: {
    marginBottom: '32px',
  },
  pageTitle: {
    fontSize: '24px',
    fontWeight: '400',
    color: '#f1f1f1',
    marginBottom: '4px',
  },
  pageSubtitle: {
    fontSize: '14px',
    color: '#aaaaaa',
  },
  statusCard: {
    background: 'rgba(33, 33, 33, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '24px',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
    transition: 'all 0.3s ease',
  },
  statusHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: '500',
    color: '#f1f1f1',
  },
  statusBadge: {
    fontSize: '13px',
    display: 'flex',
    alignItems: 'center',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '16px',
  },
  statItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  statLabel: {
    fontSize: '12px',
    color: '#aaaaaa',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  statValue: {
    fontSize: '18px',
    color: '#f1f1f1',
    fontWeight: '400',
  },
  outputCard: {
    background: 'rgba(33, 33, 33, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '24px',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
    transition: 'all 0.3s ease',
  },
  urlBox: {
    marginTop: '16px',
    padding: '16px',
    background: 'rgba(40, 40, 40, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    borderRadius: '8px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
  },
  urlHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  urlLabel: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#f1f1f1',
  },
  copyBtn: {
    padding: '6px 12px',
    fontSize: '12px',
  },
  urlValue: {
    padding: '12px',
    background: 'rgba(15, 15, 15, 0.8)',
    backdropFilter: 'blur(5px)',
    WebkitBackdropFilter: 'blur(5px)',
    borderRadius: '4px',
    color: '#3ea6ff',
    fontSize: '13px',
    fontFamily: 'monospace',
    wordBreak: 'break-all',
    marginBottom: '8px',
    border: '1px solid rgba(62, 166, 255, 0.2)',
    boxShadow: '0 0 10px rgba(62, 166, 255, 0.1)',
  },
  urlHint: {
    fontSize: '11px',
    color: '#717171',
  },
  configCard: {
    background: 'rgba(33, 33, 33, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '24px',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
    transition: 'all 0.3s ease',
  },
  configGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '16px',
    marginTop: '16px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#aaaaaa',
  },
  warningBox: {
    marginTop: '16px',
    padding: '12px 16px',
    background: 'linear-gradient(135deg, rgba(249, 171, 0, 0.15), rgba(218, 150, 0, 0.15))',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    border: '1px solid rgba(249, 171, 0, 0.4)',
    borderRadius: '8px',
    color: '#f9ab00',
    fontSize: '13px',
    display: 'flex',
    alignItems: 'center',
    boxShadow: '0 4px 15px rgba(249, 171, 0, 0.1)',
  },
  controls: {
    display: 'flex',
    gap: '16px',
    marginBottom: '24px',
    flexWrap: 'wrap',
  },
  btnLarge: {
    flex: 1,
    minWidth: '200px',
    padding: '14px 24px',
    fontSize: '15px',
  },
  infoBox: {
    padding: '16px',
    background: 'linear-gradient(135deg, rgba(62, 166, 255, 0.15), rgba(45, 143, 209, 0.15))',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    border: '1px solid rgba(62, 166, 255, 0.4)',
    borderRadius: '8px',
    color: '#3ea6ff',
    fontSize: '13px',
    display: 'flex',
    alignItems: 'center',
    boxShadow: '0 4px 15px rgba(62, 166, 255, 0.1)',
  },
};
