export const styles = {
  container: {
    maxWidth: '1920px',
    margin: '0 auto',
    padding: '24px',
  },
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '400px',
  },
  pageHeader: {
    marginBottom: '32px',
  },
  pageTitle: {
    fontSize: '24px',
    fontWeight: '400',
    color: '#f1f1f1',
    marginBottom: '4px',
  },
  pageSubtitle: {
    fontSize: '14px',
    color: '#aaaaaa',
    fontWeight: '400',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '16px',
    marginBottom: '32px',
  },
  statCard: {
    background: 'rgba(33, 33, 33, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '12px',
    padding: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
    transition: 'all 0.3s ease',
  },
  statIconWrapper: {
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, rgba(62, 166, 255, 0.2), rgba(45, 143, 209, 0.2))',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    border: '1px solid rgba(62, 166, 255, 0.3)',
    boxShadow: '0 4px 15px rgba(62, 166, 255, 0.2)',
  },
  statIcon: {
    fontSize: '24px',
    color: '#3ea6ff',
    filter: 'drop-shadow(0 0 4px rgba(62, 166, 255, 0.5))',
  },
  statContent: {
    flex: 1,
  },
  statLabel: {
    fontSize: '12px',
    color: '#aaaaaa',
    marginBottom: '4px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    fontWeight: '500',
  },
  statValue: {
    fontSize: '24px',
    fontWeight: '400',
    color: '#f1f1f1',
  },
  section: {
    marginBottom: '32px',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: '400',
    color: '#f1f1f1',
    marginBottom: '16px',
  },
  cardsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '16px',
  },
  card: {
    background: 'rgba(33, 33, 33, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
    transition: 'all 0.3s ease',
  },
  cardHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    background: 'rgba(0, 0, 0, 0.2)',
  },
  cardTitle: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#f1f1f1',
    margin: 0,
  },
  cardBody: {
    padding: '16px 20px',
  },
  infoRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
  },
  infoLabel: {
    fontSize: '13px',
    color: '#aaaaaa',
  },
  infoValue: {
    fontSize: '13px',
    color: '#f1f1f1',
    fontWeight: '400',
  },
  progressBarContainer: {
    marginTop: '12px',
  },
  progressBar: {
    width: '100%',
    height: '4px',
    background: 'rgba(48, 48, 48, 0.6)',
    borderRadius: '2px',
    overflow: 'hidden',
    marginBottom: '8px',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #3ea6ff, #4db8ff)',
    transition: 'width 0.3s ease',
    boxShadow: '0 0 10px rgba(62, 166, 255, 0.5)',
  },
  progressLabel: {
    fontSize: '12px',
    color: '#aaaaaa',
  },
  streamsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  streamItem: {
    background: 'rgba(33, 33, 33, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '8px',
    padding: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
  },
  streamThumbnail: {
    width: '64px',
    height: '36px',
    background: 'rgba(40, 40, 40, 0.8)',
    backdropFilter: 'blur(5px)',
    WebkitBackdropFilter: 'blur(5px)',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    border: '1px solid rgba(255, 255, 255, 0.05)',
  },
  thumbnailIcon: {
    fontSize: '24px',
    color: '#717171',
  },
  streamDetails: {
    flex: 1,
    minWidth: 0,
  },
  streamName: {
    fontSize: '14px',
    fontWeight: '400',
    color: '#f1f1f1',
    marginBottom: '2px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  streamUrl: {
    fontSize: '12px',
    color: '#aaaaaa',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};
