export const styles = {
  header: {
    background: 'rgba(33, 33, 33, 0.8)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    height: '56px',
    boxShadow: '0 4px 30px rgba(0, 0, 0, 0.3)',
  },
  container: {
    maxWidth: '100%',
    height: '100%',
    padding: '0 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leftSection: {
    display: 'flex',
    alignItems: 'center',
    minWidth: '200px',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    transition: 'transform 0.2s ease',
  },
  logoIcon: {
    fontSize: '28px',
    color: '#3ea6ff',
    filter: 'drop-shadow(0 0 8px rgba(62, 166, 255, 0.5))',
  },
  logoText: {
    fontSize: '20px',
    fontWeight: '500',
    color: '#f1f1f1',
    margin: 0,
    letterSpacing: '-0.5px',
  },
  nav: {
    display: 'flex',
    gap: '4px',
    flex: 1,
    justifyContent: 'center',
  },
  navButton: {
    padding: '8px 24px',
    border: 'none',
    borderRadius: '0',
    background: 'transparent',
    color: '#aaaaaa',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    position: 'relative',
    borderBottom: '3px solid transparent',
    height: '56px',
  },
  navButtonActive: {
    color: '#f1f1f1',
    borderBottomColor: '#3ea6ff',
    background: 'rgba(62, 166, 255, 0.05)',
  },
  tabIcon: {
    fontSize: '20px',
  },
  tabLabel: {
    textTransform: 'none',
    letterSpacing: '0',
  },
  rightSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    minWidth: '200px',
    justifyContent: 'flex-end',
  },
  statusIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 12px',
    background: 'rgba(40, 40, 40, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    borderRadius: '18px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
  },
  statusDot: {
    fontSize: '12px',
    color: '#cc0000',
    animation: 'pulse 2s infinite',
    filter: 'drop-shadow(0 0 4px rgba(204, 0, 0, 0.8))',
  },
  statusText: {
    fontSize: '12px',
    fontWeight: '500',
    color: '#aaaaaa',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
};
