export const styles = {
  container: {
    maxWidth: '1920px',
    margin: '0 auto',
    padding: '24px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '32px',
    flexWrap: 'wrap',
    gap: '16px',
  },
  title: {
    fontSize: '24px',
    fontWeight: '400',
    color: '#f1f1f1',
    marginBottom: '4px',
  },
  subtitle: {
    fontSize: '14px',
    color: '#aaaaaa',
    fontWeight: '400',
  },
  addButton: {
    height: '36px',
  },
  formCard: {
    background: 'rgba(33, 33, 33, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    borderRadius: '12px',
    padding: '24px',
    marginBottom: '24px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
  },
  formTitle: {
    fontSize: '16px',
    fontWeight: '500',
    marginBottom: '24px',
    color: '#f1f1f1',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '20px',
    marginBottom: '24px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#aaaaaa',
  },
  hint: {
    fontSize: '12px',
    color: '#717171',
    lineHeight: '1.5',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: '#aaaaaa',
    cursor: 'pointer',
    fontSize: '14px',
  },
  formActions: {
    display: 'flex',
    gap: '12px',
  },
  streamList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  streamCard: {
    background: 'rgba(33, 33, 33, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    borderRadius: '12px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    overflow: 'hidden',
    transition: 'all 0.3s ease',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
  },
  streamContent: {
    padding: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  streamThumbnail: {
    width: '120px',
    height: '68px',
    background: 'rgba(40, 40, 40, 0.8)',
    backdropFilter: 'blur(5px)',
    WebkitBackdropFilter: 'blur(5px)',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    border: '1px solid rgba(255, 255, 255, 0.08)',
  },
  thumbnailIcon: {
    fontSize: '40px',
    color: '#717171',
  },
  streamInfo: {
    flex: 1,
    minWidth: 0,
  },
  streamName: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#f1f1f1',
    marginBottom: '4px',
  },
  streamUrl: {
    fontSize: '12px',
    color: '#aaaaaa',
    marginBottom: '8px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  streamMeta: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  metaItem: {
    fontSize: '12px',
    color: '#aaaaaa',
  },
  metaLabel: {
    color: '#717171',
  },
  streamStatus: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    alignItems: 'flex-end',
  },
  streamActions: {
    padding: '12px 16px',
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    background: 'rgba(0, 0, 0, 0.2)',
    backdropFilter: 'blur(5px)',
    WebkitBackdropFilter: 'blur(5px)',
  },
  actionBtn: {
    fontSize: '13px',
    padding: '8px 16px',
  },
  emptyState: {
    textAlign: 'center',
    padding: '80px 20px',
    background: 'rgba(33, 33, 33, 0.6)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    borderRadius: '12px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
  },
  emptyIcon: {
    fontSize: '80px',
    color: '#717171',
    marginBottom: '16px',
    filter: 'drop-shadow(0 0 10px rgba(113, 113, 113, 0.3))',
  },
  emptyTitle: {
    fontSize: '18px',
    fontWeight: '400',
    color: '#f1f1f1',
    marginBottom: '8px',
  },
  emptyText: {
    fontSize: '14px',
    color: '#aaaaaa',
  },
};
